@startuml

start
:User logs in;
:View contract list;
if (User type) then (contractor)
:Navigates to specific contract;
:Navigate to place bid;
:Fills out bid form;
:Submit bid form;
:Redirect to contract detail;
else (contractee)
:Navigate to place contract;
:Fill out contract form;
:Submit contract;
:Redirect to contract list;
endif
end
@enduml
