@startuml

start

if (User has account) then (yes)
 :View login page;
 :User enters credentials;
 :Submit Form;
:User is redirected to loginpage;
else (no)
:View register page;
:Fill out form;
:Submit Form;
:User is authenticated and directed to homepage;

endif

stop
@enduml