@startuml
|User|
start
:Login;
:View Contract List;
:Select Contract;
if (Contractee?) then (yes)
:Navigate to Place project;
:Fill Out contract Form;
:Submit Contract;
:Redirect to Contract list;
:Choose a Contract;
if (Bid Accepted?) then (yes)
:Add bid;
else (no)
:Delete bid;
endif
else(no)
:Display Message "Access Denied";
endif
stop
@enduml
