@startuml
Actor Contractee
 
activate UserInterface
activate UserCreateView
activate LoginView
activate ContractCreateView
activate LogoutView
activate Users
activate Contracts

Contractee -> UserInterface : Register 
UserInterface -> UserCreateView: register (username, password, email, type) 
UserCreateView -> Users: create_user(User)
activate Users
Users --> UserCreateView: Confirmation
deactivate Users
UserCreateView --> UserInterface: Confirmation

Contractee -> UserInterface : Login
UserInterface -> LoginView : login(username, password) 
LoginView --> UserInterface: Confirmation


Contractee -> UserInterface : Create Contract
UserInterface -> ContractCreateView: create_contract(title, date, description)
ContractCreateView -> Contracts: create_contract(title, date, description)
activate Contracts
Contracts --> UserInterface: Contract
deactivate Contracts


Contractee -> UserInterface: Logout 
UserInterface -> LogoutView : logout(username)
LogoutView --> UserInterface : confirmation

deactivate UserInterface
deactivate UserCreateView
deactivate LoginView
deactivate ContractCreateView
deactivate LogoutView
deactivate Users
deactivate Contracts

@enduml