@startuml
left to right direction
skinparam packageStyle rectangle

rectangle "Contractor Use Cases" {
  usecase "View Contract Details" as UC2
  usecase "View Bids" as UC3
  usecase "Place Bid" as UC5
  usecase "Login" as UC11
  usecase "View Payment Details" as UC9
  usecase "Logout" as UC12
  usecase "Register" as UC13
}

actor "Contractor" as c
c --> UC11 : 1. Login
UC11 --> UC2 : 2. Update Contract
UC11 --> UC3 : 3. Update Bids
UC11 --> UC5 : 4. Update Bid
UC11 --> UC9 : 5. Update Payment
UC11 --> UC12 : 6. Return Home
c --> UC13 : 0. Register

rectangle "Client Use Cases" {
  usecase "View Contract Details" as UC15
  usecase "View Bids" as UC16
  usecase "Place Contract" as UC17
  usecase "Cancel Contract" as UC19
  usecase "View Payment Details" as UC20
  usecase "Login" as UC22
  usecase "Logout" as UC23
  usecase "Register" as UC24
}

actor "Client" as cl
cl --> UC24 : 0. Register
UC22 --> UC15 : 2. Update Contract
UC22 --> UC16 : 3. Update Bids
UC22 --> UC17 : 4. Update Contract
UC22 --> UC19 : 6. Remove Contract
UC22 --> UC20 : 7. Update Payment
UC22 --> UC23 : Return Home
cl --> UC22 : 1. Login

@enduml