@startuml
left to right direction
actor "Contractor" as c
actor "Client" as cl
rectangle Job-Bidding-Board {
  usecase "View Checkout List" as UC1
  usecase "View Contract Details" as UC2
  usecase "View Bids" as UC3
  usecase "Place Contract" as UC4
  usecase "Place Bid" as UC5
  usecase "Login" as UC6
  usecase "Logout" as UC7
  usecase "Register" as UC8
}
c --> UC1
c --> UC2
c --> UC3
c --> UC5
c --> UC6
c --> UC7
c --> UC8
cl --> UC1
cl --> UC2
cl --> UC3
cl --> UC4
cl --> UC6
cl --> UC7
cl --> UC8
@enduml