@startuml
Actor User
 
activate UserInterface
activate UserCreateView
activate Users



User -> UserInterface : Register 
UserInterface -> UserCreateView: register (username, password, email, type) 
UserCreateView -> Users: create_user(User)
activate Users
Users --> UserCreateView: Confirmation
deactivate Users
UserCreateView --> UserInterface: Confirmation

deactivate UserInterface
deactivate UserCreateView
deactivate Users

@enduml