# Generated by Django 4.0.6 on 2023-02-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_title', models.CharField(max_length=200)),
                ('agency_name', models.CharField(max_length=200)),
                ('contact_information', models.CharField(max_length=500)),
                ('bidding_end_date', models.DateField()),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('contact_information', models.CharField(max_length=500)),
                ('date_placed', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.contract')),
            ],
        ),
    ]
