# Generated by Django 4.0.6 on 2023-02-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date_placed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
